apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-orbstack-cicd-demo
  labels:
    app: argocd-orbstack-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-orbstack-cicd-demo
  template:
    metadata:
      labels:
        app: argocd-orbstack-cicd-demo
    spec:
      containers:
        - name: web
          image: ghcr.io/trionnemesis/argocd-orbstack-cicd-demo:82ff34321e5297df8d3e07d9855d806a94990255
          ports:
            - containerPort: 80
