apiVersion: v1
kind: Service
metadata:
  name: argocd-orbstack-cicd-demo
  labels:
    app: argocd-orbstack-cicd-demo
spec:
  type: ClusterIP
  selector:
    app: argocd-orbstack-cicd-demo
  ports:
    - port: 80
      targetPort: 80
